# Dockerfile example
FROM vromero/activemq-artemis:1.1.0
#FROM 192.168.99.100:5000/xenial/latest
MAINTAINER Sueleyman Vurucu <sueleyman.vurucu@amova.eu>

COPY etc-override/bootstrap.xml /var/lib/artemis/etc
COPY etc-override/broker.xml /var/lib/artemis/etc
COPY etc-override/artemis-roles.properties /var/lib/artemis/etc
COPY etc-override/artemis-users.properties /var/lib/artemis/etc


ENV ARTEMIS_MIN_MEMORY 1024M
ENV ARTEMIS_MAX_MEMORY 1024M
#ENV ARTEMIS_USERNAME wmsuser
#ENV ARTEMIS_PASSWORD wmsuser
ENV ARTEMIS_PERF_JOURNAL  AUTO

#ENV ENABLE_JMX true
#ENV JMX_PORT  1099
#ENV JMX_RMI_PORT 1098
# min version 1.5.3


#Ports
#1883 	MQTT
#5445 	HORNETQ,STOMP
#5672 	AMQP
#8161 	Web Server
#61613 	STOMP
#61616 	Core,MQTT,AMQP,HORNETQ,STOMP,Openwire


#Mount point 	                Description
#/var/lib/artemis/data 	        Holds the data files used for storing persistent messages
#/var/lib/artemis/etc 	        Hold the instance configuration files
#/var/lib/artemis/etc-override 	Hold the instance configuration files